data_path: /home/yun-liu/workspace/NIKG/dataset/
data_set: amazon-books
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id
load_col:
    inter: [user_id, item_id]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]

# environment settings
gpu_id: '2,3'
nproc: 2
world_size: 2
group_offset: 0